"""
ChronoHeroes — Import V2 complet (personnages + events + images Wikipedia)
==========================================================================
Ce script fait tout en une seule passe :
  1. Insère 7 nouveaux personnages dans `persons`
  2. Récupère leur image Wikipedia et met à jour `image_url`
  3. Insère 38 nouveaux événements dans `events`
     (inclut les events manquants pour Léonard de Vinci et Blaise Pascal)

Usage :
  python import_V2.py

Prérequis :
  pip install requests
"""

import requests
import time

# ── CONFIG ──────────────────────────────────────────────────────────────────
SUPABASE_URL = "https://geabolpfdjrclhpqxcwi.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdlYWJvbHBmZGpyY2xocHF4Y3dpIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3ODE1NTMyNiwiZXhwIjoyMDkzNzMxMzI2fQ.T4BsishTPZulNh9vBloSnMa6jq7cpobLgykXtCI0aW4"   # ← Supabase → Settings → API → service_role
# ────────────────────────────────────────────────────────────────────────────

HEADERS = {
    "apikey": SUPABASE_KEY,
    "Authorization": f"Bearer {SUPABASE_KEY}",
    "Content-Type": "application/json",
    "Prefer": "resolution=ignore-duplicates",
}

# ── 7 NOUVEAUX PERSONNAGES ──────────────────────────────────────────────────
NEW_PERSONS = [
    {
        "name": "Edgar Morin",
        "birthdate_raw": "1921-07-08",
        "deathdate_raw": "2026-05-29",
        "country": "FR",
        "geo": "philosophie-sociologie",
        "period": "xxe-contemporain",
        "tags": "philosophie,sociologie",
        "wikipedia_slug": "Edgar_Morin",
    },
    {
        "name": "Baruch Spinoza",
        "birthdate_raw": "1632-11-24",
        "deathdate_raw": "1677-02-21",
        "country": "NL",
        "geo": "philosophie",
        "period": "xviie-xviiie",
        "tags": "philosophie",
        "wikipedia_slug": "Baruch_Spinoza",
    },
    {
        "name": "Friedrich Nietzsche",
        "birthdate_raw": "1844-10-15",
        "deathdate_raw": "1900-08-25",
        "country": "DE",
        "geo": "philosophie",
        "period": "xixe",
        "tags": "philosophie,litterature",
        "wikipedia_slug": "Friedrich_Nietzsche",
    },
    {
        "name": "John Lennon",
        "birthdate_raw": "1940-10-09",
        "deathdate_raw": "1980-12-08",
        "country": "GB",
        "geo": "musique-rock",
        "period": "xxe",
        "tags": "musique-rock",
        "wikipedia_slug": "John_Lennon",
    },
    {
        "name": "Paul McCartney",
        "birthdate_raw": "1942-06-18",
        "deathdate_raw": None,
        "country": "GB",
        "geo": "musique-rock",
        "period": "xxe-contemporain",
        "tags": "musique-rock",
        "wikipedia_slug": "Paul_McCartney",
    },
    {
        "name": "George Harrison",
        "birthdate_raw": "1943-02-25",
        "deathdate_raw": "2001-11-29",
        "country": "GB",
        "geo": "musique-rock",
        "period": "xxe",
        "tags": "musique-rock",
        "wikipedia_slug": "George_Harrison",
    },
    {
        "name": "Ringo Starr",
        "birthdate_raw": "1940-07-07",
        "deathdate_raw": None,
        "country": "GB",
        "geo": "musique-rock",
        "period": "xxe-contemporain",
        "tags": "musique-rock",
        "wikipedia_slug": "Ringo_Starr",
    },
]

# ── 38 NOUVEAUX ÉVÉNEMENTS ─────────────────────────────────────────────────
# (inclut les events manquants pour Léonard de Vinci et Blaise Pascal)
NEW_EVENTS = [
    {
        "person_name": "Baruch Spinoza",
        "person_birthdate": "1632-11-24",
        "person_deathdate": "1677-02-21",
        "person_country": "NL",
        "person_geo": "philosophie",
        "person_period": "xviie-xviiie",
        "person_tags": "philosophie",
        "event_date": "1656-07-27",
        "person_age_days": 8646,
        "age_years": 23,
        "age_months": 8,
        "age_days_rem": 3,
        "age_label": "23 ans, 8 mois et 3 jours",
        "description_fr": "Excommunié (herem) par la communauté juive d\'Amsterdam — rupture radicale qui libère sa pensée philosophique",
        "category": "philosophie",
        "subcategory": "biographie",
        "importance": 5,
        "wikipedia_slug": "Baruch_Spinoza",
    },
    {
        "person_name": "Baruch Spinoza",
        "person_birthdate": "1632-11-24",
        "person_deathdate": "1677-02-21",
        "person_country": "NL",
        "person_geo": "philosophie",
        "person_period": "xviie-xviiie",
        "person_tags": "philosophie",
        "event_date": "1663-01-01",
        "person_age_days": 10995,
        "age_years": 30,
        "age_months": 1,
        "age_days_rem": 8,
        "age_label": "30 ans, 1 mois et 8 jours",
        "description_fr": "Publie son commentaire des Principes de la philosophie de Descartes, seul livre signé de son vivant",
        "category": "philosophie",
        "subcategory": "essai",
        "importance": 4,
        "wikipedia_slug": "Baruch_Spinoza",
    },
    {
        "person_name": "Baruch Spinoza",
        "person_birthdate": "1632-11-24",
        "person_deathdate": "1677-02-21",
        "person_country": "NL",
        "person_geo": "philosophie",
        "person_period": "xviie-xviiie",
        "person_tags": "philosophie",
        "event_date": "1670-01-01",
        "person_age_days": 13552,
        "age_years": 37,
        "age_months": 1,
        "age_days_rem": 8,
        "age_label": "37 ans, 1 mois et 8 jours",
        "description_fr": "Publication anonyme du Traité théologico-politique, scandale intellectuel dans toute l\'Europe protestante et catholique",
        "category": "philosophie",
        "subcategory": "essai",
        "importance": 5,
        "wikipedia_slug": "Baruch_Spinoza",
    },
    {
        "person_name": "Baruch Spinoza",
        "person_birthdate": "1632-11-24",
        "person_deathdate": "1677-02-21",
        "person_country": "NL",
        "person_geo": "philosophie",
        "person_period": "xviie-xviiie",
        "person_tags": "philosophie",
        "event_date": "1677-02-21",
        "person_age_days": 16160,
        "age_years": 44,
        "age_months": 2,
        "age_days_rem": 28,
        "age_label": "44 ans, 2 mois et 28 jours",
        "description_fr": "Meurt à La Haye à 44 ans, probablement de la tuberculose ; L\'Éthique, son chef-d\'œuvre, est publiée la même année",
        "category": "philosophie",
        "subcategory": "biographie",
        "importance": 5,
        "wikipedia_slug": "Baruch_Spinoza",
    },
    {
        "person_name": "Friedrich Nietzsche",
        "person_birthdate": "1844-10-15",
        "person_deathdate": "1900-08-25",
        "person_country": "DE",
        "person_geo": "philosophie",
        "person_period": "xixe",
        "person_tags": "philosophie,litterature",
        "event_date": "1869-05-17",
        "person_age_days": 8980,
        "age_years": 24,
        "age_months": 7,
        "age_days_rem": 2,
        "age_label": "24 ans, 7 mois et 2 jours",
        "description_fr": "Nommé professeur de philologie à Bâle à 24 ans, avant même sa soutenance de thèse — record académique",
        "category": "philosophie",
        "subcategory": "biographie",
        "importance": 4,
        "wikipedia_slug": "Friedrich_Nietzsche",
    },
    {
        "person_name": "Friedrich Nietzsche",
        "person_birthdate": "1844-10-15",
        "person_deathdate": "1900-08-25",
        "person_country": "DE",
        "person_geo": "philosophie",
        "person_period": "xixe",
        "person_tags": "philosophie,litterature",
        "event_date": "1872-01-01",
        "person_age_days": 9939,
        "age_years": 27,
        "age_months": 2,
        "age_days_rem": 17,
        "age_label": "27 ans, 2 mois et 17 jours",
        "description_fr": "Publication de La Naissance de la tragédie, première grande œuvre influencée par Wagner et Schopenhauer",
        "category": "philosophie",
        "subcategory": "essai",
        "importance": 4,
        "wikipedia_slug": "Friedrich_Nietzsche",
    },
    {
        "person_name": "Friedrich Nietzsche",
        "person_birthdate": "1844-10-15",
        "person_deathdate": "1900-08-25",
        "person_country": "DE",
        "person_geo": "philosophie",
        "person_period": "xixe",
        "person_tags": "philosophie,litterature",
        "event_date": "1883-01-01",
        "person_age_days": 13957,
        "age_years": 38,
        "age_months": 2,
        "age_days_rem": 17,
        "age_label": "38 ans, 2 mois et 17 jours",
        "description_fr": "Commence Ainsi parlait Zarathoustra, son œuvre la plus célèbre, où il développe l\'idée du Surhomme",
        "category": "philosophie",
        "subcategory": "essai",
        "importance": 5,
        "wikipedia_slug": "Friedrich_Nietzsche",
    },
    {
        "person_name": "Friedrich Nietzsche",
        "person_birthdate": "1844-10-15",
        "person_deathdate": "1900-08-25",
        "person_country": "DE",
        "person_geo": "philosophie",
        "person_period": "xixe",
        "person_tags": "philosophie,litterature",
        "event_date": "1888-01-01",
        "person_age_days": 15783,
        "age_years": 43,
        "age_months": 2,
        "age_days_rem": 17,
        "age_label": "43 ans, 2 mois et 17 jours",
        "description_fr": "Rédige en une seule année Le Crépuscule des idoles, L\'Antéchrist et Ecce Homo — fulgurance créatrice avant l\'effondrement",
        "category": "philosophie",
        "subcategory": "essai",
        "importance": 5,
        "wikipedia_slug": "Friedrich_Nietzsche",
    },
    {
        "person_name": "Friedrich Nietzsche",
        "person_birthdate": "1844-10-15",
        "person_deathdate": "1900-08-25",
        "person_country": "DE",
        "person_geo": "philosophie",
        "person_period": "xixe",
        "person_tags": "philosophie,litterature",
        "event_date": "1889-01-03",
        "person_age_days": 16151,
        "age_years": 44,
        "age_months": 2,
        "age_days_rem": 19,
        "age_label": "44 ans, 2 mois et 19 jours",
        "description_fr": "Effondrement mental à Turin — s\'effondre dans la rue en embrassant un cheval et sombre dans la folie définitivement",
        "category": "philosophie",
        "subcategory": "biographie",
        "importance": 5,
        "wikipedia_slug": "Friedrich_Nietzsche",
    },
    {
        "person_name": "John Lennon",
        "person_birthdate": "1940-10-09",
        "person_deathdate": "1980-12-08",
        "person_country": "GB",
        "person_geo": "musique-rock",
        "person_period": "xxe",
        "person_tags": "musique-rock",
        "event_date": "1962-08-15",
        "person_age_days": 7980,
        "age_years": 21,
        "age_months": 10,
        "age_days_rem": 6,
        "age_label": "21 ans, 10 mois et 6 jours",
        "description_fr": "Les Beatles enregistrent Love Me Do chez EMI, premier single d\'un groupe qui va révolutionner la musique mondiale",
        "category": "arts",
        "subcategory": "musique",
        "importance": 5,
        "wikipedia_slug": "John_Lennon",
    },
    {
        "person_name": "John Lennon",
        "person_birthdate": "1940-10-09",
        "person_deathdate": "1980-12-08",
        "person_country": "GB",
        "person_geo": "musique-rock",
        "person_period": "xxe",
        "person_tags": "musique-rock",
        "event_date": "1966-06-01",
        "person_age_days": 9366,
        "age_years": 25,
        "age_months": 7,
        "age_days_rem": 23,
        "age_label": "25 ans, 7 mois et 23 jours",
        "description_fr": "Sortie de Revolver, album des Beatles qui marque un tournant vers la psychédélie et la sophistication musicale",
        "category": "arts",
        "subcategory": "musique",
        "importance": 5,
        "wikipedia_slug": "John_Lennon",
    },
    {
        "person_name": "John Lennon",
        "person_birthdate": "1940-10-09",
        "person_deathdate": "1980-12-08",
        "person_country": "GB",
        "person_geo": "musique-rock",
        "person_period": "xxe",
        "person_tags": "musique-rock",
        "event_date": "1971-10-11",
        "person_age_days": 11324,
        "age_years": 31,
        "age_months": 0,
        "age_days_rem": 2,
        "age_label": "31 ans, 0 mois et 2 jours",
        "description_fr": "Sortie d\'Imagine, hymne pacifiste devenu l\'une des chansons les plus connues et reprises du monde entier",
        "category": "arts",
        "subcategory": "musique",
        "importance": 5,
        "wikipedia_slug": "John_Lennon",
    },
    {
        "person_name": "John Lennon",
        "person_birthdate": "1940-10-09",
        "person_deathdate": "1980-12-08",
        "person_country": "GB",
        "person_geo": "musique-rock",
        "person_period": "xxe",
        "person_tags": "musique-rock",
        "event_date": "1980-12-08",
        "person_age_days": 14670,
        "age_years": 40,
        "age_months": 1,
        "age_days_rem": 29,
        "age_label": "40 ans, 1 mois et 29 jours",
        "description_fr": "Assassiné devant son immeuble du Dakota à New York par Mark David Chapman — choc mondial",
        "category": "arts",
        "subcategory": "biographie",
        "importance": 5,
        "wikipedia_slug": "John_Lennon",
    },
    {
        "person_name": "Paul McCartney",
        "person_birthdate": "1942-06-18",
        "person_deathdate": None,
        "person_country": "GB",
        "person_geo": "musique-rock",
        "person_period": "xxe-contemporain",
        "person_tags": "musique-rock",
        "event_date": "1962-08-15",
        "person_age_days": 7363,
        "age_years": 20,
        "age_months": 1,
        "age_days_rem": 28,
        "age_label": "20 ans, 1 mois et 28 jours",
        "description_fr": "Les Beatles enregistrent Love Me Do chez EMI, lançant la Beatlemania qui va déferler sur le monde entier",
        "category": "arts",
        "subcategory": "musique",
        "importance": 5,
        "wikipedia_slug": "Paul_McCartney",
    },
    {
        "person_name": "Paul McCartney",
        "person_birthdate": "1942-06-18",
        "person_deathdate": None,
        "person_country": "GB",
        "person_geo": "musique-rock",
        "person_period": "xxe-contemporain",
        "person_tags": "musique-rock",
        "event_date": "1967-06-01",
        "person_age_days": 9114,
        "age_years": 24,
        "age_months": 11,
        "age_days_rem": 14,
        "age_label": "24 ans, 11 mois et 14 jours",
        "description_fr": "Sortie de Sgt. Pepper\'s Lonely Hearts Club Band, souvent classé meilleur album de tous les temps par la critique",
        "category": "arts",
        "subcategory": "musique",
        "importance": 5,
        "wikipedia_slug": "Paul_McCartney",
    },
    {
        "person_name": "Paul McCartney",
        "person_birthdate": "1942-06-18",
        "person_deathdate": None,
        "person_country": "GB",
        "person_geo": "musique-rock",
        "person_period": "xxe-contemporain",
        "person_tags": "musique-rock",
        "event_date": "1970-04-10",
        "person_age_days": 10158,
        "age_years": 27,
        "age_months": 9,
        "age_days_rem": 23,
        "age_label": "27 ans, 9 mois et 23 jours",
        "description_fr": "Annonce officiellement la séparation des Beatles dans un communiqué de presse — fin d\'une époque musicale",
        "category": "arts",
        "subcategory": "musique",
        "importance": 5,
        "wikipedia_slug": "Paul_McCartney",
    },
    {
        "person_name": "Paul McCartney",
        "person_birthdate": "1942-06-18",
        "person_deathdate": None,
        "person_country": "GB",
        "person_geo": "musique-rock",
        "person_period": "xxe-contemporain",
        "person_tags": "musique-rock",
        "event_date": "1973-01-01",
        "person_age_days": 11155,
        "age_years": 30,
        "age_months": 6,
        "age_days_rem": 14,
        "age_label": "30 ans, 6 mois et 14 jours",
        "description_fr": "Sortie de Band on the Run avec Wings, album qui consacre son succès en solo malgré les sceptiques",
        "category": "arts",
        "subcategory": "musique",
        "importance": 4,
        "wikipedia_slug": "Paul_McCartney",
    },
    {
        "person_name": "George Harrison",
        "person_birthdate": "1943-02-25",
        "person_deathdate": "2001-11-29",
        "person_country": "GB",
        "person_geo": "musique-rock",
        "person_period": "xxe",
        "person_tags": "musique-rock",
        "event_date": "1962-08-15",
        "person_age_days": 7111,
        "age_years": 19,
        "age_months": 5,
        "age_days_rem": 21,
        "age_label": "19 ans, 5 mois et 21 jours",
        "description_fr": "Les Beatles enregistrent Love Me Do chez EMI, George Harrison en est le plus jeune membre à 19 ans",
        "category": "arts",
        "subcategory": "musique",
        "importance": 4,
        "wikipedia_slug": "George_Harrison",
    },
    {
        "person_name": "George Harrison",
        "person_birthdate": "1943-02-25",
        "person_deathdate": "2001-11-29",
        "person_country": "GB",
        "person_geo": "musique-rock",
        "person_period": "xxe",
        "person_tags": "musique-rock",
        "event_date": "1968-11-01",
        "person_age_days": 9381,
        "age_years": 25,
        "age_months": 8,
        "age_days_rem": 7,
        "age_label": "25 ans, 8 mois et 7 jours",
        "description_fr": "Sort Wonderwall Music, devenant le premier Beatle à publier un album solo",
        "category": "arts",
        "subcategory": "musique",
        "importance": 4,
        "wikipedia_slug": "George_Harrison",
    },
    {
        "person_name": "George Harrison",
        "person_birthdate": "1943-02-25",
        "person_deathdate": "2001-11-29",
        "person_country": "GB",
        "person_geo": "musique-rock",
        "person_period": "xxe",
        "person_tags": "musique-rock",
        "event_date": "1970-11-27",
        "person_age_days": 10137,
        "age_years": 27,
        "age_months": 9,
        "age_days_rem": 2,
        "age_label": "27 ans, 9 mois et 2 jours",
        "description_fr": "Sort All Things Must Pass, triple album acclamé par la critique et meilleur album solo d\'un ex-Beatle selon beaucoup",
        "category": "arts",
        "subcategory": "musique",
        "importance": 5,
        "wikipedia_slug": "George_Harrison",
    },
    {
        "person_name": "George Harrison",
        "person_birthdate": "1943-02-25",
        "person_deathdate": "2001-11-29",
        "person_country": "GB",
        "person_geo": "musique-rock",
        "person_period": "xxe",
        "person_tags": "musique-rock",
        "event_date": "1971-08-01",
        "person_age_days": 10384,
        "age_years": 28,
        "age_months": 5,
        "age_days_rem": 7,
        "age_label": "28 ans, 5 mois et 7 jours",
        "description_fr": "Organise le Concert for Bangladesh au Madison Square Garden, premier grand concert humanitaire de l\'histoire du rock",
        "category": "arts",
        "subcategory": "musique",
        "importance": 5,
        "wikipedia_slug": "George_Harrison",
    },
    {
        "person_name": "Ringo Starr",
        "person_birthdate": "1940-07-07",
        "person_deathdate": None,
        "person_country": "GB",
        "person_geo": "musique-rock",
        "person_period": "xxe-contemporain",
        "person_tags": "musique-rock",
        "event_date": "1962-08-15",
        "person_age_days": 8074,
        "age_years": 22,
        "age_months": 1,
        "age_days_rem": 8,
        "age_label": "22 ans, 1 mois et 8 jours",
        "description_fr": "Rejoint les Beatles comme batteur en remplaçant Pete Best — le line-up définitif est formé, la légende commence",
        "category": "arts",
        "subcategory": "musique",
        "importance": 5,
        "wikipedia_slug": "Ringo_Starr",
    },
    {
        "person_name": "Ringo Starr",
        "person_birthdate": "1940-07-07",
        "person_deathdate": None,
        "person_country": "GB",
        "person_geo": "musique-rock",
        "person_period": "xxe-contemporain",
        "person_tags": "musique-rock",
        "event_date": "1973-11-02",
        "person_age_days": 12171,
        "age_years": 33,
        "age_months": 3,
        "age_days_rem": 26,
        "age_label": "33 ans, 3 mois et 26 jours",
        "description_fr": "Sort Ringo, son meilleur album solo, avec des contributions inédites de Lennon, McCartney et Harrison réunis",
        "category": "arts",
        "subcategory": "musique",
        "importance": 4,
        "wikipedia_slug": "Ringo_Starr",
    },
    {
        "person_name": "Ringo Starr",
        "person_birthdate": "1940-07-07",
        "person_deathdate": None,
        "person_country": "GB",
        "person_geo": "musique-rock",
        "person_period": "xxe-contemporain",
        "person_tags": "musique-rock",
        "event_date": "1981-01-01",
        "person_age_days": 14788,
        "age_years": 40,
        "age_months": 5,
        "age_days_rem": 25,
        "age_label": "40 ans, 5 mois et 25 jours",
        "description_fr": "Participe à All Those Years Ago, hommage à Lennon enregistré avec McCartney et Harrison — première réunion post-Beatles",
        "category": "arts",
        "subcategory": "musique",
        "importance": 4,
        "wikipedia_slug": "Ringo_Starr",
    },
    {
        "person_name": "Edgar Morin",
        "person_birthdate": "1921-07-08",
        "person_deathdate": "2026-05-29",
        "person_country": "FR",
        "person_geo": "philosophie-sociologie",
        "person_period": "xxe-contemporain",
        "person_tags": "philosophie,sociologie",
        "event_date": "1951-01-01",
        "person_age_days": 10769,
        "age_years": 29,
        "age_months": 5,
        "age_days_rem": 24,
        "age_label": "29 ans, 5 mois et 24 jours",
        "description_fr": "Publication de L\'Homme et la Mort, son premier grand essai philosophique, qui fonde sa réflexion sur la condition humaine",
        "category": "philosophie",
        "subcategory": "essai",
        "importance": 4,
        "wikipedia_slug": "Edgar_Morin",
    },
    {
        "person_name": "Edgar Morin",
        "person_birthdate": "1921-07-08",
        "person_deathdate": "2026-05-29",
        "person_country": "FR",
        "person_geo": "philosophie-sociologie",
        "person_period": "xxe-contemporain",
        "person_tags": "philosophie,sociologie",
        "event_date": "1967-01-01",
        "person_age_days": 16613,
        "age_years": 45,
        "age_months": 5,
        "age_days_rem": 24,
        "age_label": "45 ans, 5 mois et 24 jours",
        "description_fr": "Publie La Commune en France, reportage sociologique sur Plozévet — naissance de la sociologie du présent",
        "category": "science",
        "subcategory": "sociologie",
        "importance": 4,
        "wikipedia_slug": "Edgar_Morin",
    },
    {
        "person_name": "Edgar Morin",
        "person_birthdate": "1921-07-08",
        "person_deathdate": "2026-05-29",
        "person_country": "FR",
        "person_geo": "philosophie-sociologie",
        "person_period": "xxe-contemporain",
        "person_tags": "philosophie,sociologie",
        "event_date": "1977-01-01",
        "person_age_days": 20266,
        "age_years": 55,
        "age_months": 5,
        "age_days_rem": 24,
        "age_label": "55 ans, 5 mois et 24 jours",
        "description_fr": "Publication du premier tome de La Méthode, œuvre monumentale sur la pensée complexe en 6 volumes sur 30 ans",
        "category": "philosophie",
        "subcategory": "essai",
        "importance": 5,
        "wikipedia_slug": "Edgar_Morin",
    },
    {
        "person_name": "Edgar Morin",
        "person_birthdate": "1921-07-08",
        "person_deathdate": "2026-05-29",
        "person_country": "FR",
        "person_geo": "philosophie-sociologie",
        "person_period": "xxe-contemporain",
        "person_tags": "philosophie,sociologie",
        "event_date": "2026-05-29",
        "person_age_days": 38311,
        "age_years": 104,
        "age_months": 10,
        "age_days_rem": 21,
        "age_label": "104 ans, 10 mois et 21 jours",
        "description_fr": "S\'éteint à Paris à 104 ans, figure tutélaire de la pensée complexe et de l\'humanisme du XXe et XXIe siècle",
        "category": "philosophie",
        "subcategory": "biographie",
        "importance": 5,
        "wikipedia_slug": "Edgar_Morin",
    },
    {
        "person_name": "Léonard de Vinci",
        "person_birthdate": "1452-04-15",
        "person_deathdate": "1519-05-02",
        "person_country": "IT",
        "person_geo": "arts-sciences",
        "person_period": "renaissance",
        "person_tags": "arts-peinture,science-invention",
        "event_date": "1472-01-01",
        "person_age_days": 7200,
        "age_years": 19,
        "age_months": 8,
        "age_days_rem": 17,
        "age_label": "19 ans, 8 mois et 17 jours",
        "description_fr": "Admis à la guilde des peintres de Florence — début officiel de sa carrière artistique sous Verrocchio",
        "category": "arts",
        "subcategory": "peinture",
        "importance": 4,
        "wikipedia_slug": "Léonard_de_Vinci",
    },
    {
        "person_name": "Léonard de Vinci",
        "person_birthdate": "1452-04-15",
        "person_deathdate": "1519-05-02",
        "person_country": "IT",
        "person_geo": "arts-sciences",
        "person_period": "renaissance",
        "person_tags": "arts-peinture,science-invention",
        "event_date": "1490-01-01",
        "person_age_days": 13775,
        "age_years": 37,
        "age_months": 8,
        "age_days_rem": 17,
        "age_label": "37 ans, 8 mois et 17 jours",
        "description_fr": "Réalise L\'Homme de Vitruve, symbole universel des proportions parfaites du corps humain",
        "category": "science",
        "subcategory": "anatomie",
        "importance": 5,
        "wikipedia_slug": "Léonard_de_Vinci",
    },
    {
        "person_name": "Léonard de Vinci",
        "person_birthdate": "1452-04-15",
        "person_deathdate": "1519-05-02",
        "person_country": "IT",
        "person_geo": "arts-sciences",
        "person_period": "renaissance",
        "person_tags": "arts-peinture,science-invention",
        "event_date": "1519-05-02",
        "person_age_days": 24487,
        "age_years": 67,
        "age_months": 0,
        "age_days_rem": 17,
        "age_label": "67 ans, 0 mois et 17 jours",
        "description_fr": "Meurt à Amboise en France, dans les bras du roi François Ier selon la légende, laissant des milliers de pages de carnets",
        "category": "arts",
        "subcategory": "biographie",
        "importance": 5,
        "wikipedia_slug": "Léonard_de_Vinci",
    },
    {
        "person_name": "Léonard de Vinci",
        "person_birthdate": "1452-04-15",
        "person_deathdate": "1519-05-02",
        "person_country": "IT",
        "person_geo": "arts-sciences",
        "person_period": "renaissance",
        "person_tags": "arts-peinture,science-invention",
        "event_date": "1482-01-01",
        "person_age_days": 10853,
        "age_years": 29,
        "age_months": 8,
        "age_days_rem": 17,
        "age_label": "29 ans, 8 mois et 17 jours",
        "description_fr": "S\'installe à Milan à la cour de Ludovic Sforza comme ingénieur, musicien et peintre — début de sa période la plus productive",
        "category": "arts",
        "subcategory": "biographie",
        "importance": 4,
        "wikipedia_slug": "Léonard_de_Vinci",
    },
    {
        "person_name": "Léonard de Vinci",
        "person_birthdate": "1452-04-15",
        "person_deathdate": "1519-05-02",
        "person_country": "IT",
        "person_geo": "arts-sciences",
        "person_period": "renaissance",
        "person_tags": "arts-peinture,science-invention",
        "event_date": "1498-01-01",
        "person_age_days": 16697,
        "age_years": 45,
        "age_months": 8,
        "age_days_rem": 17,
        "age_label": "45 ans, 8 mois et 17 jours",
        "description_fr": "Réalise les fresques de la salle des Axes au château Sforza et travaille sur de nombreux projets d\'ingénierie militaire",
        "category": "science",
        "subcategory": "invention",
        "importance": 3,
        "wikipedia_slug": "Léonard_de_Vinci",
    },
    {
        "person_name": "Léonard de Vinci",
        "person_birthdate": "1452-04-15",
        "person_deathdate": "1519-05-02",
        "person_country": "IT",
        "person_geo": "arts-sciences",
        "person_period": "renaissance",
        "person_tags": "arts-peinture,science-invention",
        "event_date": "1516-01-01",
        "person_age_days": 23270,
        "age_years": 63,
        "age_months": 8,
        "age_days_rem": 17,
        "age_label": "63 ans, 8 mois et 17 jours",
        "description_fr": "Accepte l\'invitation de François Ier et s\'installe au Clos Lucé à Amboise — les trois dernières années de sa vie en France",
        "category": "arts",
        "subcategory": "biographie",
        "importance": 4,
        "wikipedia_slug": "Léonard_de_Vinci",
    },
    {
        "person_name": "Léonard de Vinci",
        "person_birthdate": "1452-04-15",
        "person_deathdate": "1519-05-02",
        "person_country": "IT",
        "person_geo": "arts-sciences",
        "person_period": "renaissance",
        "person_tags": "arts-peinture,science-invention",
        "event_date": "1513-01-01",
        "person_age_days": 22175,
        "age_years": 60,
        "age_months": 8,
        "age_days_rem": 17,
        "age_label": "60 ans, 8 mois et 17 jours",
        "description_fr": "Peint Saint Jean-Baptiste, son dernier tableau achevé, symbole mystérieux à l\'ambiguïté troublante — aujourd\'hui au Louvre",
        "category": "arts",
        "subcategory": "peinture",
        "importance": 4,
        "wikipedia_slug": "Léonard_de_Vinci",
    },
    {
        "person_name": "Blaise Pascal",
        "person_birthdate": "1623-06-19",
        "person_deathdate": "1662-08-19",
        "person_country": "FR",
        "person_geo": "philosophie-science",
        "person_period": "xviie-xviiie",
        "person_tags": "science-medecine,philosophie",
        "event_date": "1639-01-01",
        "person_age_days": 5675,
        "age_years": 15,
        "age_months": 6,
        "age_days_rem": 13,
        "age_label": "15 ans, 6 mois et 13 jours",
        "description_fr": "Rédige son Essai sur les coniques à 15 ans, stupéfiant Descartes qui refuse d\'abord d\'y croire",
        "category": "science",
        "subcategory": "mathematiques",
        "importance": 5,
        "wikipedia_slug": "Blaise_Pascal",
    },
    {
        "person_name": "Blaise Pascal",
        "person_birthdate": "1623-06-19",
        "person_deathdate": "1662-08-19",
        "person_country": "FR",
        "person_geo": "philosophie-science",
        "person_period": "xviie-xviiie",
        "person_tags": "science-medecine,philosophie",
        "event_date": "1654-11-23",
        "person_age_days": 11480,
        "age_years": 31,
        "age_months": 5,
        "age_days_rem": 4,
        "age_label": "31 ans, 5 mois et 4 jours",
        "description_fr": "Nuit de feu : expérience mystique intense qui le convertit définitivement au jansénisme de Port-Royal",
        "category": "philosophie",
        "subcategory": "spirituel",
        "importance": 5,
        "wikipedia_slug": "Blaise_Pascal",
    },
    {
        "person_name": "Blaise Pascal",
        "person_birthdate": "1623-06-19",
        "person_deathdate": "1662-08-19",
        "person_country": "FR",
        "person_geo": "philosophie-science",
        "person_period": "xviie-xviiie",
        "person_tags": "science-medecine,philosophie",
        "event_date": "1662-08-19",
        "person_age_days": 14306,
        "age_years": 39,
        "age_months": 2,
        "age_days_rem": 0,
        "age_label": "39 ans, 2 mois et 0 jours",
        "description_fr": "Meurt à Paris à seulement 39 ans, laissant les Pensées inachevées — publiées à titre posthume en 1670",
        "category": "philosophie",
        "subcategory": "biographie",
        "importance": 5,
        "wikipedia_slug": "Blaise_Pascal",
    },
]


def get_wikipedia_image(slug: str) -> str | None:
    """Récupère l'image principale Wikipedia (essaie FR puis EN)."""
    for lang in ["fr", "en"]:
        try:
            url = (
                f"https://{lang}.wikipedia.org/w/api.php"
                f"?action=query&titles={requests.utils.quote(slug)}"
                f"&prop=pageimages&format=json&pithumbsize=400"
            )
            r = requests.get(url, timeout=10,
                             headers={"User-Agent": "ChronoHeroes/1.0"})
            pages = r.json()["query"]["pages"]
            page = next(iter(pages.values()))
            img = page.get("thumbnail", {}).get("source")
            if img:
                return img
        except Exception:
            pass
    return None


def get_person_id(name: str) -> str | None:
    """Récupère l'id Supabase d'un personnage par son nom."""
    r = requests.get(
        f"{SUPABASE_URL}/rest/v1/persons",
        headers=HEADERS,
        params={"name": f"eq.{name}", "select": "id"},
    )
    data = r.json()
    return data[0]["id"] if data else None


def insert_persons():
    """Vérifie si le personnage existe, le crée si besoin, récupère l'image Wikipedia."""
    print("\n=== Insertion des personnages + images Wikipedia ===")
    for p in NEW_PERSONS:
        # 1. Vérifier si le personnage existe déjà
        person_id = get_person_id(p["name"])

        if person_id:
            print(f"  ~ {p['name']} déjà en base (id: {person_id[:8]}…)")
        else:
            # 2. Créer le personnage
            payload = {k: v for k, v in p.items() if v is not None}
            r = requests.post(
                f"{SUPABASE_URL}/rest/v1/persons",
                headers=HEADERS,
                json=payload,
            )
            if r.status_code in (200, 201):
                person_id = get_person_id(p["name"])
                print(f"  ✓ {p['name']} créé (id: {person_id[:8] if person_id else '?'}…)")
            else:
                print(f"  ✗ {p['name']} erreur {r.status_code}: {r.text[:200]}")
                continue
            time.sleep(0.2)

        # 3. Récupérer et mettre à jour l'image Wikipedia
        slug = p.get("wikipedia_slug", p["name"].replace(" ", "_"))
        img = get_wikipedia_image(slug)
        if img:
            requests.patch(
                f"{SUPABASE_URL}/rest/v1/persons",
                headers=HEADERS,
                params={"id": f"eq.{person_id}"},
                json={"image_url": img},
            )
            print(f"    🖼  Image OK → {img[:65]}")
        else:
            print(f"    – Pas d'image trouvée pour {p['name']}")
        time.sleep(0.4)


def insert_events():
    """Insère les nouveaux événements, liés à leur person_id."""
    print("\n=== Insertion des événements ===")
    ok = 0
    ko = 0
    for e in NEW_EVENTS:
        person_id = get_person_id(e["person_name"])
        if not person_id:
            print(f"  ✗ Personnage introuvable : {e['person_name']}")
            ko += 1
            continue
        payload = {
            "person_id": person_id,
            "person_name": e["person_name"],
            "event_date_raw": e["event_date"],
            "person_age_days": e["person_age_days"],
            "age_years": e["age_years"],
            "age_months": e["age_months"],
            "age_days_rem": e["age_days_rem"],
            "age_label": e["age_label"],
            "description_fr": e["description_fr"],
            "category": e["category"],
            "subcategory": e["subcategory"],
            "importance": e["importance"],
        }
        r = requests.post(
            f"{SUPABASE_URL}/rest/v1/events",
            headers=HEADERS,
            json=payload,
        )
        if r.status_code in (200, 201):
            print(f"  ✓ {e['person_name']} — {e['event_date']}")
            ok += 1
        else:
            print(f"  ✗ {e['person_name']} — {e['event_date']} ({r.status_code}: {r.text[:80]})")
            ko += 1
        time.sleep(0.15)
    print(f"\n  {ok} events insérés, {ko} erreurs")


def main():
    print("=== ChronoHeroes — Import V2 (personnages + images + events) ===")
    if SUPABASE_KEY == "VOTRE_SERVICE_ROLE_KEY":
        print("\n⚠ Renseigne ta SUPABASE_KEY en haut du fichier avant de lancer !")
        return
    insert_persons()   # crée les personnages ET récupère les images Wikipedia
    insert_events()    # insère les 38 nouveaux événements
    print("\n=== Import terminé ! Vérifie dans Supabase → Table Editor. ===")


if __name__ == "__main__":
    main()